In [1]:
import numpy as np
import pandas as pd

from pandas import Series, DataFrame

In [2]:
#Split based on  quality
#Apply a function to it to compress it further
#Combine the diluted information together

In [5]:
dframe = pd.read_csv('winequality-red.csv', sep = ';')
dframe.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [27]:
#Goal: Finding the highest alcohol content for each quality range

#Step 1: Sorting by descending order of alcohol

dframe.sort_values('alcohol', ascending = False, inplace = True)
dframe.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,rank
652,15.9,0.36,0.65,7.5,0.096,22.0,71.0,0.99760,2.98,0.84,14.9,5,1
588,5.0,0.42,0.24,2.0,0.060,19.0,50.0,0.99170,3.72,0.74,14.0,8,1
142,5.2,0.34,0.00,1.8,0.050,27.0,63.0,0.99160,3.68,0.79,14.0,6,1
144,5.2,0.34,0.00,1.8,0.050,27.0,63.0,0.99160,3.68,0.79,14.0,6,2
1270,5.0,0.38,0.01,1.6,0.048,26.0,60.0,0.99084,3.70,0.75,14.0,6,3

In [28]:
#Step 2: Creating an apply function which will set ranks

def ranker(df):
    dframe['rank'] = np.arange(len(df)) + 1 
    return df

In [32]:
#Step 3: Groupby to split by quality, Apply function to rank in each quality range

dframe = dframe.groupby('quality').apply(ranker)

AttributeError: Cannot access callable attribute 'groupby' of 'DataFrameGroupBy' objects, try using the 'apply' method

In [33]:
#Number of wines in each quality range

num_qual = dframe['quality'].value_counts()
num_qual

quality  quality
3        3           10
4        4           53
5        5          681
6        6          638
7        7          199
8        8           18
Name: quality, dtype: int64

In [36]:
#Combining: Showing the highest alcohol content in each quality range

dframe['rank' == 1].head(len(num_qual))

KeyError: 'Column not found: False'